# Generated by Django 5.1 on 2024-09-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('education', models.TextField(max_length=100)),
                ('experience', models.TextField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('certifications', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Skills', models.ManyToManyField(to='recruiter.skills')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobpost')),
                ('job_seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobseeker')),
            ],
        ),
    ]
